# Generated by Django 5.0.1 on 2024-01-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_body_comment_text_comment_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user',
        ),
    ]
