# Generated by Django 5.0.1 on 2024-01-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_post_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
