# Generated by Django 5.0.1 on 2024-01-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_image_url_product_sku_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=100)),
                ('message_position', models.CharField(choices=[('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Customer Service', 'Customer Service')], max_length=20)),
                ('message_cv', models.FileField(blank=True, null=True, upload_to='cv_uploads/')),
                ('message', models.TextField()),
                ('message_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
