# Generated by Django 5.0.1 on 2024-01-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_careers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careers',
            old_name='message_cv',
            new_name='cv',
        ),
        migrations.RenameField(
            model_name='careers',
            old_name='message_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='careers',
            old_name='message_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='careers',
            old_name='message_position',
            new_name='position',
        ),
    ]
